# Generated by Django 2.1 on 2018-10-08 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('stream', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Law', 'Law'), ('Arts', 'Arts')], default='Engineering', max_length=258)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256)),
                ('degree', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('exam', models.CharField(max_length=20)),
                ('course_duration', models.IntegerField()),
                ('eligibility', models.CharField(max_length=223)),
                ('course_detail', models.CharField(max_length=256)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('stream', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Law', 'Law'), ('Arts', 'Arts')], default='Engineering', max_length=258)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Exam', models.CharField(choices=[('JEE Main', 'JEE Main'), ('JEE Advance', 'JEE Advance'), ('VITEEE', 'VITEEE'), ('GATE', 'GATE')], default='GATE', max_length=258)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=256)),
                ('hobby_choices', models.CharField(choices=[('None', 'Please Select'), ('Music', 'Music'), ('Sports', 'Sports')], default='None', max_length=25)),
                ('hobby_name', models.CharField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(default='', max_length=250)),
                ('qualification', models.CharField(default='', max_length=250)),
                ('subjects', models.CharField(default='', max_length=250)),
                ('percentage', models.CharField(default='', max_length=250)),
                ('Description', models.CharField(default='', max_length=250)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subcoursepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=254)),
                ('Total_fees', models.IntegerField()),
                ('subcourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hob', to='web_app.Course_page')),
            ],
        ),
        migrations.AddField(
            model_name='hobby_details',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hob', to='web_app.Student_profile'),
        ),
    ]
