# Generated by Django 2.1 on 2018-10-31 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streambranch', models.CharField(max_length=222)),
                ('streamdegree', models.CharField(max_length=122)),
                ('Stream', models.CharField(max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='course_page',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='course_page',
            name='updated_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='course_page',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course_page',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='course_page',
            name='exam',
        ),
        migrations.AddField(
            model_name='course_page',
            name='exam',
            field=models.ManyToManyField(blank=True, default=None, to='web_app.Exam_detail'),
        ),
        migrations.AddField(
            model_name='course_page',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.College_detail'),
        ),
    ]
