# Generated by Django 2.1 on 2018-10-08 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_course_page_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_page',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
