# Generated by Django 2.1 on 2018-10-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20181031_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_page',
            name='slug',
            field=models.SlugField(default='hello welcome'),
        ),
    ]
