# Generated by Django 2.1 on 2018-10-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20181008_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_page',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
