# Generated by Django 2.1 on 2018-11-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20181031_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_detail',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
