# Generated by Django 2.1 on 2018-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_course_page_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='streams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streambranch', models.CharField(max_length=222)),
                ('streamdegree', models.CharField(max_length=122)),
                ('mainstream', models.CharField(max_length=122)),
            ],
        ),
    ]
