# Generated by Django 2.1 on 2018-10-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_streams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streams',
            old_name='mainstream',
            new_name='Stream',
        ),
    ]
