# Generated by Django 2.1 on 2018-10-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20181010_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_page',
            name='exam',
        ),
        migrations.AddField(
            model_name='course_page',
            name='exam',
            field=models.ManyToManyField(blank=True, default=None, to='web_app.Exam_detail'),
        ),
    ]
